### ISSUE TITLE
Binary-search-cpp.me

### ISSUE THREAD

**Issue by Manish4Kumar** [ossamamehmood/Hacktoberfest2022#1142]
BINARY SEARCH IN CPP
Binary Search is a method to find the required element in a sorted array by repeatedly halving the array and searching in the half.

This method is done by starting with the whole array. Then it is halved. If the required data value is greater than the element at the middle of the array, then the upper half of the array is considered. Otherwise, the lower half is considered. This is done continuously until either the required data value is obtained or the remaining array is empty.

This content to help you understand concepts, and how to implement binary search, and this also helps to interview purposes.

#include
using namespace std;
int binarySearch(int arr[], int p, int r, int num) {
   if (p <= r) {
      int mid = (p + r)/2;
      if (arr[mid] == num)
         return mid ;
      if (arr[mid] > num)
         return binarySearch(arr, p, mid-1, num);
      if (arr[mid] < num)
         return binarySearch(arr, mid+1, r, num);
   }
   return -1;
}
int main(void) {
   int arr[] = {1, 3, 7, 15, 18, 20, 25, 33, 36, 40};
   int n = sizeof(arr)/ sizeof(arr[0]);
   int num;
   cout << "Enter the number to search: \n";
   cin >> num;
   int index = binarySearch (arr, 0, n-1, num);
   if(index == -1){
      cout<< num <<" is not present in the array";
   }else{
      cout<< num <<" is present at index "<< index <<" in the array";
   }
   return 0;
}

Output:-
Enter the number to search
20
20 is present at index 5 in the array

**Comment by Manish4Kumar** [comment]
pls merge my prs

**Comment by Sandyy07** [comment]
Kindly Please assign me this issue.

**Comment by Ankita-278** [comment]
can you pls assign me this issue

**Comment by Amanm2003** [comment]
May i
