### ISSUE TITLE
I want to add a frontend page on the topic of Best Study Platform in India

### ISSUE THREAD

**Issue by Ramank2002** [ossamamehmood/Hacktoberfest2022#1160]
Hello sir ,
I'm Raman Kumar Gupta  , GitHub Id - Ramank2002 
I did the contribution by adding a new frontend page on the topic of Best Study Platform using HTML  5 and CSS 3 in the repo by following all the rules.
Kindly consider it , & for this I'll very grateful to you.
Thankyou.

**Comment by adityahacker109251** [comment]
sir I can be perfect to make your frontend page for your website. i have done a educational website before i can make that for any of the plateform.such as android, ios, windows and linux
