### ISSUE TITLE
Is this repo Excluded from hacktober2022?

### ISSUE THREAD

**Issue by ajeyprasand** [ossamamehmood/Hacktoberfest2022#1184]

**Comment by Mittelblut9** [comment]
Yes
<img width="480" alt="Screenshot 2022-10-05 at 12 04 05" src="https://user-images.githubusercontent.com/67608550/194035358-60016fd6-f9f1-410b-8b85-22715a8634ea.png">

**Comment by ossamamehmood** [comment]
Yes! But you can go for an alternate way where you can fork and merge in your own fork repo!!!
