### ISSUE TITLE
Is this repo excluded from Hactoberfest ?

### ISSUE THREAD

**Issue by iamrahul8** [ossamamehmood/Hacktoberfest2022#1434]
![image](https://user-images.githubusercontent.com/72541381/194394564-6b54bf01-7aaa-4dfc-ba4f-b8011caaadcb.png)
@ossamamehmood

**Comment by goswamiprad** [comment]
@iamrahul8  I believe it is. As it is showing the same in my profile as well.

**Comment by ossamamehmood** [comment]
Big YES, you can explore the way to get PR's!
