### ISSUE TITLE
Create a Calculator using any language 

### ISSUE THREAD

**Issue by TryToLearnProgramming** [ossamamehmood/Hacktoberfest2022#1716]
Create a specific directory
Can use any programming language

**Comment by TryToLearnProgramming** [comment]
Can I do this?

**Comment by codemastershrey** [comment]
can you assign me?

**Comment by SiddhiKhade** [comment]
I would really appreciate it if you assigned this task to me, thanks!

**Comment by SiddhiKhade** [comment]
@ossamamehmood Hi, thank you for assigning this issue to me. I have created a calculator in python which performs basic arithmetic operations on 'n' numbers until the user wishes to quit.
