### ISSUE TITLE
This repo is EXCLUDED from hactoberfest

### ISSUE THREAD

**Issue by kjain05** [ossamamehmood/Hacktoberfest2022#173]
Your PR/MR was submitted to a repository that has been excluded from Hacktoberfest as it does not follow the values of the event. It will not count towards your participation.
please verify for the same.

**Comment by ossamamehmood** [comment]
I'll look at the repo to help people get there for the first PR. However, I'll try to find a Solution. Thanks for letting me know : )

**Comment by ossamamehmood** [comment]
@kjain05 Do you know any solution to get approved the repo?
