### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by dheerajrao20** [ossamamehmood/Hacktoberfest2022#1827]
Hey, I have an Awesome **_QR Code generator_**.

I want to add it under <a href="https://hacktoberfest.com/">**_Hacktoberfest 2022_**</a>

Tech Stacks : **_Python_**

Kindly assign this Issue to me under **_hacktoberfest 2022_** tag.

![image](https://user-images.githubusercontent.com/89007097/194723209-0f4600b3-6562-4990-9e31-3a49e940f21a.png)

**Comment by dheerajrao20** [comment]
**_@ossamamehmood_** Kindly assign this issue to me under **_hacktoberfest 2022._**

**Comment by weirdwizard20** [comment]
[html5-qrcode-master.zip](https://github.com/ossamamehmood/Hacktoberfest2022/files/9740121/html5-qrcode-master.zip)

**Comment by dheerajrao20** [comment]
Hey **_@weirdwizard20_** I am using python only and will add codes under python folder you can use websites folder to add this code.
But create a new issue separate for website.

**Comment by dheerajrao20** [comment]
@ossamamehmood Kindly assign this issue to me only.
