### ISSUE TITLE
Want to make grocery application 

### ISSUE THREAD

**Issue by PranavSagar** [ossamamehmood/Hacktoberfest2022#2049]
## Using ArrayList in java with the simplest and most understandable code    

# it will include the following operations

-  To show the list of grocery items.
-  To add an item to the list.
-  To modify an item in the list
-  to remove an item from the list.
-  To search for an item in the list.
-  To quit the application.

**Comment by Shinchan2803** [comment]
can u assign me this issue

**Comment by Shinchan2803** [comment]
i completed this issue and give the pull req so please merged the code
