### ISSUE TITLE
Want to add tic tac toe game using C++

### ISSUE THREAD

**Issue by AnuranjN** [ossamamehmood/Hacktoberfest2022#2134]
I want to add code for a tic tac toe game using C++

**Comment by AnuranjN** [comment]
Kindly assign me for this task

**Comment by mdzeeshan-2** [comment]
Hii @ossamamehmood Please assign this issue to me.

**Comment by psantosh16** [comment]
Hey , 
I want to contribute in Hacktoberfest as it is my first time can you assign this issue to me .
It will be great for me and thank you. @ossamamehmood
