### ISSUE TITLE
Add Right View of Binary Tree

### ISSUE THREAD

**Issue by AndroGari** [ossamamehmood/Hacktoberfest2022#2179]
I would like to Add Right View of Binary Tree

**Comment by rprithvi653** [comment]
Please Assign This Issue to me, I'll solve this issue As Soon As Possible.

**Comment by deepakchowdary19** [comment]
can you assign this to me

**Comment by Arpit-Gulgulia** [comment]
@ossamamehmood , can you assign this to me? I would like to take this issue as for Hacktoberfest.

**Comment by Arpit-Gulgulia** [comment]
@ossamamehmood , can you please review and merge the PR. Thanks!
