### ISSUE TITLE
Longest Common Subsequence (Dynamic Programming problem)

### ISSUE THREAD

**Issue by keshav-guptaa** [ossamamehmood/Hacktoberfest2022#2190]
I want to add a solution to this problem in C++ (Cpp). @ossamamehmood please assign this task to me under **hacktoberfest.**

**Comment by deepakchowdary19** [comment]
@ossamamehmood  can you assign this to me as i can make my first pr

**Comment by abhi-1407** [comment]
please assign this issue to me,I want to add the C++ solution

**Comment by yashvardhansingh15** [comment]
please assign this issue, I want to merge a file
