### ISSUE TITLE
Find loop in a linked list using c++

### ISSUE THREAD

**Issue by priyaastha** [ossamamehmood/Hacktoberfest2022#2382]
Please assign me this under hacktoberfest.

**Comment by SakshamSharma07** [comment]
@priyaastha  assign this to me ,i want to work on it.

**Comment by arnav-vivian** [comment]
please assing this to me i want to give a solution to this problem.

**Comment by dhruv1345** [comment]
@ossamamehmood Please assign me this issue. I have a good knowledge in C++ and I can solve this question with good time complexity as well.
