### ISSUE TITLE
Height of a binary tree in C++

### ISSUE THREAD

**Issue by vinayassrao** [ossamamehmood/Hacktoberfest2022#2444]
Hello, I would love to contribute to this problem..Please, assign me this

**Comment by krishna1912** [comment]
Hello sir, I want to contribute in it. Kindly give me a chance to do it.

**Comment by Aashi111aggarwal** [comment]
sir please assign this issue to me @vinayassrao

**Comment by Aashi111aggarwal** [comment]
please assign this  to me, i want to contribute @ossamamehmood
