### ISSUE TITLE
Creating Documentation and Rearrange the files

### ISSUE THREAD

**Issue by theDreamer911** [ossamamehmood/Hacktoberfest2022#2484]
This repo is great, but the structure is so bad. I want to contribute to the ML project, but I got a lot of trash from many developers. What I said trash, because it doesn't correctly arrange, let me arrange this and create some rules.

**Comment by ossamamehmood** [comment]
You can follow up the rule you want I'll add up : )

**Comment by ossamamehmood** [comment]
I rearrange the repo time to time : )

**Comment by theDreamer911** [comment]
alrighttt, thank you I will do it now
