### ISSUE TITLE
This repo is excluded

### ISSUE THREAD

**Issue by aaryahjolia** [ossamamehmood/Hacktoberfest2022#255]

**Comment by ossamamehmood** [comment]
Do you know any solution to get approved the repo?

**Comment by aaryahjolia** [comment]
> Do you know any solution to get approved the repo?
I think for 2022, It can't be included.
But for future purpose, Make a repo where you don't need to only contribute our name but any one function in any language like a sorting code in c++, A simple website in HTML, etc.

**Comment by ossamamehmood** [comment]
Good Idea I'll plan a better way to implement will check the possible ways. Glad to hear @aaryahjolia
