### ISSUE TITLE
Evaluate Reverse Polish Notation(Leetcode 150)

### ISSUE THREAD

**Issue by khusboobothra** [ossamamehmood/Hacktoberfest2022#2552]
Evaluate the value of an arithmetic expression in [Reverse Polish Notation](http://en.wikipedia.org/wiki/Reverse_Polish_notation).
Valid operators are +, -, *, and /. Each operand may be an integer or another expression.

Input: tokens = ["2","1","+","3","*"]
Output: 9
Explanation: ((2 + 1) * 3) = 9

**Comment by khusboobothra** [comment]
I would like to solve this problem in C++.

**Comment by Kritikmahajan** [comment]
@ossamamehmood  plz assign this issue  to me .
i will solve this inn cpp.

**Comment by SakshamSharma07** [comment]
@khusboobothra  please assign me this problem , i can solve this in CPP

**Comment by Serajhub** [comment]
Please assign this to me

**Comment by Ishita2407** [comment]
Kindly assign this issue to me , I would like to help

**Comment by Mridul-2003** [comment]
I would like to solve it in python

**Comment by Kritikmahajan** [comment]
Sorry to say but your repository is excluded from hacktoberfest 😔
