### ISSUE TITLE
Java Program for Rotating a Linked List

### ISSUE THREAD

**Issue by sweekriti121** [ossamamehmood/Hacktoberfest2022#2686]
Hi, I want to add a java program for rotating a linked list in this repository, kindly assign it to me under the hacktoberfest label.

**Comment by sweekriti121** [comment]
#2687

**Comment by jawadkhanpk** [comment]
Hey, I have a strong profile in DSA, won lot of coding competitions and Hackathons, I would really appreciate if you can assign me this issue. Thanks.
Happy Coding😇

**Comment by jawadkhanpk** [comment]
Hey, it is taking lot of time to clone is it normal even I have good internet connection?
