### ISSUE TITLE
Excluded from Hacktoberfest

### ISSUE THREAD

**Issue by Kedar-27** [ossamamehmood/Hacktoberfest2022#308]

**Comment by ritikbanger** [comment]
![Screenshot from 2022-10-01 19-54-38](https://user-images.githubusercontent.com/47841501/193414201-d6705bed-107f-4f3d-a675-259553781933.png)

**Comment by ossamamehmood** [comment]
I know @Kedar-27 & @ritikbanger, but there's no solution for the current issue to solve. However, if you have any way to solve please let me know. Thank You!

**Comment by ritikbanger** [comment]
There is no solution for this, You can create another repo with helpful content or update your readme.md and send the PR creators to this repo: [https://github.com/ritikbanger/Hacktoberfest2022-DSA](https://github.com/ritikbanger/Hacktoberfest2022-DSA)

**Comment by ossamamehmood** [comment]
Alright, I saw your DSA code repo for Hacktoberfest 2022
