### ISSUE TITLE
can i add my profile photo and data as part of hacktoberfest 2022

### ISSUE THREAD

**Issue by anmolkulshrestha** [ossamamehmood/Hacktoberfest2022#367]

**Comment by ossamamehmood** [comment]
## Instructions-

- Fork this Repository using the button at the top
- Clone your forked repository to your pc ( git clone "url from clone option.)
- Create a new branch for your modifications (ie. `git branch new-user` and check it out `git checkout new-user` or simply do `git checkout -b new-user`)
- Add your profile image in `static/images/` ( use drag and drop option or upload by commands.)
- Add your profile data in `content/participant/`
- Add your files (`git add -A`), commit (`git commit -m "added myself"`) and push (`git push origin new-user`)
- Create a pull request
- Star this repository

# How to make your first Pull Request

Replace `<YOUR-USERNAME>` with your GitHub username in this guide.

## 1. Add your profile picture to the folder

Add a picture picture of your choice in `static/images/`. Accepted files are **png** and **jpg**, should be squared and minimum size 544x544 pixels. Ex.

```
static/images/<YOUR-USERNAME>.png
```


## 2. Add your profile information

Create a markdown file in your folder following the convention `content/participant/<YOUR-USERNAME>.md`. Ex.

```
content/participant/<YOUR-USERNAME>.md/
```

Copy the next template into your file, delete the boilerplate data and fill the information with yours.

```
---
name: YOURNAME
institution/company: INSTITUTION_NAME
github:USERNAME
---
```

## 4. Wait for Pull Request to merge

## 5. Celebrate - you've done your first pull request!!

```py
'''
always make more then 4 pull request
lets you have made only 4 pull request to different projects
but one project is excluded from hackoctoberfest event then your pull request will not be count and 
then you have remains 3 valid pull request if these projects is not excluded.
if you fail to make 4 pull request then you cant get swags or t-shirts.
i will recommend you make pull request to your own repo which is very very saffest side for you..
keep in mind that repo has hacktoberfest topic..
'''
```

## + Follow Me : } Quick Approval of Pull Request

```py
'''
To get approval of the pull request much quicker (`Follow Me`)🚀
'''
```

<tr><td align="center"><a href="https://github.com/ossamamehmood"><kbd><img src="https://avatars3.githubusercontent.com/ossamamehmood?size=100" width="100px;" alt=""/></kbd><br /><sub><b>Ossama Mehmood</b></sub></a><br /></td>

</tr>
