### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by 2devyank** [ossamamehmood/Hacktoberfest2022#423]
I would like to add quick sort algorithm in java

**Comment by ossamamehmood** [comment]
Go a head

**Comment by ArSin2002** [comment]
i would love to work on this quicksort in python @ossamamehmood

**Comment by alphaCoderR** [comment]
Can i work here??

**Comment by Mohit-Kukreja-2002** [comment]
Can I add quick sort using c++?
