### ISSUE TITLE
Wanted to add Reverse Alphabet Pyramid Pattern Program in Python

### ISSUE THREAD

**Issue by piyush-sri** [ossamamehmood/Hacktoberfest2022#436]
ABCDEFGHI
 ABCDEFG
  ABCDE
   ABC
    A
It looks like this, Please assign me this issue.

**Comment by alphaCoderR** [comment]
Can i work here??

**Comment by ossamamehmood** [comment]
Go A Head!

**Comment by piyush-sri** [comment]
I made a pull request by adding the ReverseAlphabetPattern.py File Please have a look and merge it
