### ISSUE TITLE
Reverse a Linked List in java

### ISSUE THREAD

**Issue by janhavikale06** [ossamamehmood/Hacktoberfest2022#476]

**Comment by ramvikrams** [comment]
sir you assign me this i can reverse a linked list in java

**Comment by janhavikale06** [comment]
hey @ossamamehmood , I would like to add a code for reverse a LL in java. Please assign me this issue.

**Comment by Hack7023** [comment]
please assign this to me.

**Comment by vaibhu4coding** [comment]
Good Afternoon, @ossamamehmood, I want to add code of reverse linked list in Java.
Requesting to assign me in this issue.
I hope you are doing well

**Comment by Karmpatel960** [comment]
Hey,@ossamamehmood  Can you Please assign this  issue to me. I would like to add  reverse linked list in it.

**Comment by ossamamehmood** [comment]
Assigned to @everyone
