### ISSUE TITLE
Ceaser cipher in c++

### ISSUE THREAD

**Issue by rajdip-b** [ossamamehmood/Hacktoberfest2022#568]
# Description 
This program would allow users to encrypt their messages into cipher text using the ceaser cipher technique.

## Example
Plain text: `hello`
shift: `5`
crypt: `mjqqt`

Can I be assigned this issue under Hacktoberfest2022?

**Comment by Ayushchaudhary-Github** [comment]
can you assign this to me because it's not done yet?

**Comment by rajdip-b** [comment]
Hey @ossamamehmood, do I no longer work on the issue?
