### ISSUE TITLE
Height of Binary Tree

### ISSUE THREAD

**Issue by Dharansh-Neema** [ossamamehmood/Hacktoberfest2022#584]
**Recursively calculating height of left and right subtrees of a node**

**Comment by Dharansh-Neema** [comment]
@ossamamehmood Can you please assign me to this issue.

**Comment by debjitpurohit** [comment]
please assing me on this issue

**Comment by Kshitij-1373** [comment]
Please assign me this issue..

**Comment by Dharansh-Neema** [comment]
@ossamamehmood this issue is created by me.
 Please assign this to me

**Comment by Dharansh-Neema** [comment]
#625 Binary Tree Height Code Added
